// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qggjmtlmcnqmptbttlxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnZ2ptdGxtY25xbXB0YnR0bHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzYyODAsImV4cCI6MjA2NDcxMjI4MH0.ir4T4guZbPp3j1dF3A-F5XGRKfoC7feXYMKUcyt3VBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);